apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil
  namespace: dev
  labels:
    app: wil
spec:
  selector:
    matchLabels:
      app: wil
  template:
    metadata:
      labels:
        app: wil
    spec:
      containers:
      - name: wil
        image: wil42/playground:v2
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: svc-wil
spec:
  selector:
    app: wil
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8888
